#!perl


use strict;
use Cwd;
use File::Spec;
use File::Basename;
use Digest::MD5;
use Digest::SHA;
use IO::File;
use Win32::Clipboard;
use Encode;

select( STDOUT ); 
$| = 1;
my $cwd0;
my $choss=1;
while (1) {
print "请输入要计算hash的目录:\n";
my $mlgm=5;
while ($mlgm != -1) {
$cwd0=<STDIN>;
while ($cwd0=~m/\\\\|\/\/|\!|\?|\<|\>|\||\*|\"/g){
	print "请输入正确的目录\n" ;
	$cwd0=<STDIN>;
	$mlgm--;
	if ($mlgm == 0){
		print "喵了个咪！能不能输入个正确的目录\n";
		exit 0;
	}
	next;
}
$cwd0=~s#\/#\\#g;
chomp ($cwd0);
if (chdir ($cwd0)){
	$mlgm = -1;
	}
else{	
	$mlgm--;
	if ($mlgm == 0){
		print "咪了个喵！都说了";
		$mlgm =3;
	}
	print "输入的目录不存在\n";
	} 
next;
}
print "=======================\n";
print "请选择要计算的hash类型:\n";
print "1.MD5\n";
print "2.SHA256\n";
print "3.重选目录\n";
print "=======================\n";
$choss=<STDIN>;
chomp($choss);
last if $choss == 1 || $choss == 2;
}

my @files = glob q{*};
my $extc = ".txt";
my $ext = "MD5" if $choss == 1;
$ext = "SHA256" if $choss == 2;
my $exta =$ext.$extc;
my $hhhh=$cwd0."\\".$ext.$extc;
my $FFILE = IO::File->new($exta,q{>} ) or die "Couldn't open $exta:$!";
select( $FFILE ); 
$| = 1;
my $gctime = localtime;
print $FFILE "# $ext checksums generated by Hash_15_Pl \n# Generated $gctime\n\n";
print STDOUT "# $ext checksums generated by Hash_15_Pl \n# Generated $gctime\n\n";
foreach my $file(@files)
{
	Encode::_utf8_off($cwd0);
	Encode::_utf8_off($file);
	my $path = File::Spec->catfile( $cwd0, $file );
	&filelist($path);
}
$FFILE->close;
my $cpfile;
if (-e $hhhh) {
	my $FHH=IO::File->new($hhhh) or die "Couldn't open '$hhhh': $!";
    binmode($FHH);
	if ($choss == 1) {
        $cpfile = Digest::MD5->new->addfile(*$FHH)->hexdigest;
    }else{
        $cpfile = Digest::SHA->new(256)->addfile(*$FHH)->hexdigest;
    }      
	$FHH->close;	
}
print STDOUT "生成的$exta 文件的$ext 值为:\n\t $cpfile \n该值已copy到剪贴板\n";
my $CLIP = Win32::Clipboard();
$CLIP->Set($cpfile);
print STDOUT "end!\n";
<>;


sub filelist{
	my $path = shift @_;
	my $file_name = basename $path;
	if(-d $file_name)
	{		
		chdir $path or die "can't chdir $path:$!";
		my $cwd = getcwd;
		my @files = glob q{*};
		my $count = 0;
		foreach my $file(@files)
		{
			$count++;
			Encode::_utf8_off($cwd);
			Encode::_utf8_off($file);
			my $path = File::Spec->catfile( $cwd, $file );
			&filelist($path);
		}
		if ($count eq @files)
		{
			my $dir_name = dirname $path; 
			chdir "$dir_name\.." or die "can't chdir $dir_name\..:$!";
		}
	}
	else
	{
		my $hash;
		my $FH=IO::File->new($path) or die "Couldn't open '$path': $!";
        binmode($FH);
        if ($choss == 1) {
			$hash = Digest::MD5->new->addfile(*$FH)->hexdigest;
		}else{
		    $hash = Digest::SHA->new(256)->addfile(*$FH)->hexdigest;
		}        
        $FH->close;
        my $cwd1=$cwd0;
        $cwd1=~s/\/|\\/\#/g;
        $path=~s/\\|\//\#/g;
        $path=~s#$cwd1#\.#gi;
        $path=~s/\#/\\/g;        
		print $FFILE "<======$hash======> $path\n";
        print STDOUT "<======$hash======> $path\n";
	}
}